name: DABRCS
version: '${project.version}'
main: com.bawnorton.dabrsc.DABRCS
api-version: '1.21'
commands:
  dabrcs:
    description: Set DABR Config
    usage: /<command> <config> <value>
    aliases: [dabrcs]
